; Text-mode services built on the SC-8 pixel graphics routines.
; Cursor positions are 6x8 cell coordinates (53 columns by 30 rows).
.include "lib_gfx.asm"
.include "fonts/font5x7.asm"

.address 0x0700

SCREEN_CLEAR:
    CALL GFX_CLEAR
    LDI R0, 0
    LDI R7, 0x430A
    ST R7, R0
    INC R7
    ST R7, R0
    RET

SCREEN_SET_CURSOR:
    LDWS R0, 2
    LDWS R1, 4
    LDI R7, 0x430A
    ST R7, R0
    INC R7
    ST R7, R1
    RET

SCREEN_GET_CURSOR:
    LDI R7, 0x430A
    LD R0, R7
    INC R7
    LD R1, R7
    LDI R2, 8
    LDI R6, 0
SCREEN_GET_CURSOR_SHIFT:
    ADD R1, R1
    DEC R2
    CMP R2, R6
    BZ SCREEN_GET_CURSOR_PACK
    JMP SCREEN_GET_CURSOR_SHIFT
SCREEN_GET_CURSOR_PACK:
    ADD R0, R1
    RET

SCREEN_PRINT:
    LDWS R0, 2
    LDI R7, 0x430C
    STW R7, R0
    MOVSP R7
    LDI R6, 4
    ADD R7, R6
    LD R0, R7
    LDI R7, 0x431C
    ST R7, R0
    LDWS R0, 5
    LDI R7, 0x4318
    ST R7, R0
SCREEN_PRINT_NEXT:
    LDI R7, 0x430C
    LDW R4, R7
    LDI R7, 0x431C
    LD R5, R7
    CALLX SCREEN_EXPAND_POINTER
    LD R0, R4
    INC R4
    CALLX SCREEN_SAVE_PRINT_POINTER
    LDI R7, 0
    CMP R0, R7
    BZX SCREEN_PRINT_DONE
    LDI R7, 0xC3
    CMP R0, R7
    BZX SCREEN_PRINT_UTF8
    LDI R7, 0x4318
    LD R1, R7
    CALLX SCREEN_PUTCHAR
    JMPX SCREEN_PRINT_NEXT
SCREEN_PRINT_UTF8:
    LDI R7, 0x430C
    LDW R4, R7
    LDI R7, 0x431C
    LD R5, R7
    CALLX SCREEN_EXPAND_POINTER
    LD R0, R4
    INC R4
    CALLX SCREEN_SAVE_PRINT_POINTER
    LDI R7, 0x96
    CMP R0, R7
    BZX SCREEN_PRINT_O_UMLAUT
    LDI R7, 0xB6
    CMP R0, R7
    BZX SCREEN_PRINT_O_UMLAUT_LOWER
    LDI R7, 0x84
    CMP R0, R7
    BZX SCREEN_PRINT_A_UMLAUT
    LDI R7, 0xA4
    CMP R0, R7
    BZX SCREEN_PRINT_A_UMLAUT_LOWER
    LDI R7, 0x85
    CMP R0, R7
    BZX SCREEN_PRINT_A_RING
    LDI R7, 0xA5
    CMP R0, R7
    BZX SCREEN_PRINT_A_RING_LOWER
    LDI R0, 63
    JMPX SCREEN_PRINT_UTF8_READY
SCREEN_PRINT_O_UMLAUT:
    LDI R0, 214
    JMPX SCREEN_PRINT_UTF8_READY
SCREEN_PRINT_O_UMLAUT_LOWER:
    LDI R0, 246
    JMPX SCREEN_PRINT_UTF8_READY
SCREEN_PRINT_A_UMLAUT:
    LDI R0, 196
    JMPX SCREEN_PRINT_UTF8_READY
SCREEN_PRINT_A_UMLAUT_LOWER:
    LDI R0, 228
    JMPX SCREEN_PRINT_UTF8_READY
SCREEN_PRINT_A_RING:
    LDI R0, 197
    JMPX SCREEN_PRINT_UTF8_READY
SCREEN_PRINT_A_RING_LOWER:
    LDI R0, 229
SCREEN_PRINT_UTF8_READY:
    LDI R7, 0x4318
    LD R1, R7
    CALLX SCREEN_PUTCHAR
    JMPX SCREEN_PRINT_NEXT
SCREEN_PRINT_DONE:
    RET

SCREEN_PUTCHAR:
    LDI R7, 0x4308
    ST R7, R0
    LDI R7, 0x4318
    ST R7, R1
    MOV R2, R0
    LDI R7, 10
    CMP R2, R7
    BZX SCREEN_NEWLINE
    LDI R7, 13
    CMP R2, R7
    BZX SCREEN_NEWLINE

    LDI R7, 31
    CMP R2, R7
    BCX SCREEN_SPACE_GLYPH
    LDI R7, 127
    CMP R2, R7
    BCX SCREEN_ASCII_GLYPH
    LDI R7, 196
    CMP R2, R7
    BZX SCREEN_GLYPH_A_UMLAUT
    LDI R7, 197
    CMP R2, R7
    BZX SCREEN_GLYPH_A_RING
    LDI R7, 214
    CMP R2, R7
    BZX SCREEN_GLYPH_O_UMLAUT
    LDI R7, 228
    CMP R2, R7
    BZX SCREEN_GLYPH_A_UMLAUT_LOWER
    LDI R7, 229
    CMP R2, R7
    BZX SCREEN_GLYPH_A_RING_LOWER
    LDI R7, 246
    CMP R2, R7
    BZX SCREEN_GLYPH_O_UMLAUT_LOWER
SCREEN_SPACE_GLYPH:
    LDI R2, 1
    JMPX SCREEN_GLYPH_READY
SCREEN_ASCII_GLYPH:
    LDI R7, 31
    SUB R2, R7
    JMPX SCREEN_GLYPH_READY
SCREEN_GLYPH_O_UMLAUT_LOWER:
    LDI R2, 96
    JMPX SCREEN_GLYPH_READY
SCREEN_GLYPH_A_UMLAUT_LOWER:
    LDI R2, 97
    JMPX SCREEN_GLYPH_READY
SCREEN_GLYPH_A_RING_LOWER:
    LDI R2, 98
    JMPX SCREEN_GLYPH_READY
SCREEN_GLYPH_O_UMLAUT:
    LDI R2, 99
    JMPX SCREEN_GLYPH_READY
SCREEN_GLYPH_A_UMLAUT:
    LDI R2, 100
    JMPX SCREEN_GLYPH_READY
SCREEN_GLYPH_A_RING:
    LDI R2, 101
SCREEN_GLYPH_READY:
    LDI R7, 0x4308
    ST R7, R2
    INC R7
    LDI R2, 0
    ST R7, R2

    LDI R7, 0x430A
    LD R2, R7
    LDI R4, 0
    LDI R5, 6
    LDI R6, 0
SCREEN_PIXEL_X_LOOP:
    CMP R2, R6
    BZX SCREEN_PIXEL_X_DONE
    ADD R4, R5
    DEC R2
    JMPX SCREEN_PIXEL_X_LOOP
SCREEN_PIXEL_X_DONE:
    LDI R7, 0x4314
    STW R7, R4
    LDI R7, 0x430B
    LD R2, R7
    LDI R4, 0
    LDI R5, 8
SCREEN_PIXEL_Y_LOOP:
    CMP R2, R6
    BZX SCREEN_PIXEL_Y_DONE
    ADD R4, R5
    DEC R2
    JMPX SCREEN_PIXEL_Y_LOOP
SCREEN_PIXEL_Y_DONE:
    LDI R7, 0x4316
    STW R7, R4

    LDI R7, 0x4314
    LDW R0, R7
    LDI R7, 0x4316
    LDW R1, R7
    LDI R2, 6
    LDI R3, 8
    LDI R4, 0
    CALL GFX_RECT

    LDI R7, 0x4314
    LDW R0, R7
    LDI R7, 0x4316
    LDW R1, R7
    LDI R2, 0x4308
    LDI R7, 0x4318
    LD R3, R7
    CALL GFX_TEXT

    LDI R7, 0x430A
    LD R2, R7
    INC R2
    ST R7, R2
    LDI R6, 53
    CMP R2, R6
    BZX SCREEN_WRAP_ROW
    JMPX SCREEN_PUTCHAR_DONE
SCREEN_WRAP_ROW:
    LDI R2, 0
    ST R7, R2
    INC R7
    LD R2, R7
    INC R2
    LDI R6, 30
    CMP R2, R6
    BZX SCREEN_WRAP_TOP
    ST R7, R2
    JMPX SCREEN_PUTCHAR_DONE
SCREEN_WRAP_TOP:
    LDI R2, 0
    ST R7, R2
SCREEN_PUTCHAR_DONE:
    RET

SCREEN_NEWLINE:
    LDI R7, 0x430A
    LDI R2, 0
    ST R7, R2
    INC R7
    LD R2, R7
    INC R2
    LDI R6, 30
    CMP R2, R6
    BZX SCREEN_NEWLINE_TOP
    ST R7, R2
    RET
SCREEN_NEWLINE_TOP:
    LDI R2, 0
    ST R7, R2
    RET

SCREEN_INPUT:
    LDWS R0, 2
    LDI R7, 0x4310
    STW R7, R0
    MOVSP R7
    LDI R6, 4
    ADD R7, R6
    LD R0, R7
    LDI R7, 0x431D
    ST R7, R0
    LDWS R0, 5
    LDI R7, 0x430E
    ST R7, R0
    LDI R0, 0
    LDI R7, 0x430F
    ST R7, R0
    LDWS R0, 7
    LDI R7, 0x4313
    ST R7, R0
SCREEN_INPUT_POLL:
    LDI R4, 0xFFFF
    INC R4
    MOV R5, R4
    ADD R4, R5
    ADD R4, R5
    ADD R4, R5
    LDI R5, 0x3000
    ADD R4, R5
    LD R0, R4
    LDI R7, 0
    CMP R0, R7
    BZX SCREEN_INPUT_POLL
    ST R4, R7
    LDI R7, 0x4312
    ST R7, R0
    LDI R7, 13
    CMP R0, R7
    BZX SCREEN_INPUT_DONE
    LDI R7, 10
    CMP R0, R7
    BZX SCREEN_INPUT_DONE
    LDI R7, 8
    CMP R0, R7
    BZX SCREEN_INPUT_BACKSPACE
    LDI R7, 127
    CMP R0, R7
    BZX SCREEN_INPUT_BACKSPACE
    LDI R7, 0x430F
    LD R5, R7
    LDI R7, 0x430E
    LD R6, R7
    CMP R5, R6
    BCX SCREEN_INPUT_STORE
    JMPX SCREEN_INPUT_POLL
SCREEN_INPUT_STORE:
    LDI R7, 0x4310
    LDW R4, R7
    LDI R7, 0x431D
    LD R5, R7
    CALLX SCREEN_EXPAND_POINTER
    LDI R7, 0x4312
    LD R0, R7
    ST R4, R0
    INC R4
    CALLX SCREEN_SAVE_INPUT_POINTER
    LDI R7, 0x430F
    LD R5, R7
    INC R5
    ST R7, R5
    LDI R7, 0x4313
    LD R1, R7
    CALLX SCREEN_PUTCHAR
    JMPX SCREEN_INPUT_POLL
SCREEN_INPUT_BACKSPACE:
    LDI R7, 0x430F
    LD R5, R7
    LDI R6, 0
    CMP R5, R6
    BZX SCREEN_INPUT_POLL
    DEC R5
    ST R7, R5
    LDI R7, 0x4310
    LDW R4, R7
    LDI R7, 0x431D
    LD R5, R7
    CALLX SCREEN_EXPAND_POINTER
    DEC R4
    CALLX SCREEN_SAVE_INPUT_POINTER
    LDI R0, 0
    ST R4, R0
    LDI R0, 32
    LDI R1, 0
    CALLX SCREEN_BACKSPACE
    JMPX SCREEN_INPUT_POLL
SCREEN_BACKSPACE:
    LDI R7, 0x430A
    LD R2, R7
    LDI R6, 0
    CMP R2, R6
    BZX SCREEN_BACKSPACE_DONE
    DEC R2
    ST R7, R2
    CALLX SCREEN_PUTCHAR
SCREEN_BACKSPACE_DONE:
    RET
SCREEN_INPUT_DONE:
    LDI R7, 0x4310
    LDW R4, R7
    LDI R7, 0x431D
    LD R5, R7
    CALLX SCREEN_EXPAND_POINTER
    LDI R0, 0
    ST R4, R0
    LDI R7, 0x430F
    LD R0, R7
    LDI R7, 0x4313
    LD R1, R7
    LDI R0, 10
    CALLX SCREEN_PUTCHAR
    LDI R7, 0x430F
    LD R0, R7
    RET

SCREEN_EXPAND_POINTER:
    LDI R6, 0xFFFF
    INC R6
    LDI R7, 0
SCREEN_EXPAND_POINTER_LOOP:
    CMP R5, R7
    BZX SCREEN_EXPAND_POINTER_DONE
    ADD R4, R6
    DEC R5
    CMP R5, R7
    BZX SCREEN_EXPAND_POINTER_DONE
    JMPX SCREEN_EXPAND_POINTER_LOOP
SCREEN_EXPAND_POINTER_DONE:
    RET

SCREEN_SAVE_PRINT_POINTER:
    LDI R7, 0x430C
    STW R7, R4
    JMPX SCREEN_SAVE_POINTER_HIGH_PRINT

SCREEN_SAVE_POINTER_HIGH_PRINT:
    MOV R5, R4
    LDI R6, 0xFFFF
    INC R6
    LDI R7, 0
SCREEN_SAVE_POINTER_HIGH_PRINT_LOOP:
    CMP R5, R6
    BCX SCREEN_SAVE_POINTER_HIGH_PRINT_DONE
    SUB R5, R6
    INC R7
    JMPX SCREEN_SAVE_POINTER_HIGH_PRINT_LOOP
SCREEN_SAVE_POINTER_HIGH_PRINT_DONE:
    LDI R5, 0x431C
    ST R5, R7
    RET

SCREEN_SAVE_INPUT_POINTER:
    LDI R7, 0x4310
    STW R7, R4
    MOV R5, R4
    LDI R6, 0xFFFF
    INC R6
    LDI R7, 0
SCREEN_SAVE_INPUT_POINTER_LOOP:
    CMP R5, R6
    BCX SCREEN_SAVE_INPUT_POINTER_DONE
    SUB R5, R6
    INC R7
    JMPX SCREEN_SAVE_INPUT_POINTER_LOOP
SCREEN_SAVE_INPUT_POINTER_DONE:
    LDI R5, 0x431D
    ST R5, R7
    RET
